---
title: "Diary Entry"
author: "Loy Yee Keen"
date: "`r Sys.Date()`"
output: pdf_document
---
# Week 9

### (1) What is the topic that you have finalised? (Answer in 1 or 2 sentences).
The topic that I have finalised is "Names", specifically the names that parents give their babies.

### (2) What are the data sources that you have curated so far? (Answer 1 or 2 sentences).
I have curated a dataset consisting of a list of names given to babies born in the US each year, the gender of the babies, and the count of each name per gender. The data sources span from the years 1880 to 2022. These data sources are extracted from the website of the United States Social Security Administration, an independent agency of the U.S. federal government.

# Week 10

### (1) What is the question that you are going to answer? (Answer: One sentence that ends with a question mark that could act like the title of your data story),

Are American parents giving their children more and more gender-neutral names?

### (2) Why is this an important question? (Answer: 3 sentences, each of which has some evidence, e.g., “According to the United Nations...” to justify why the question you have chosen is important)

The Council of Europe underscores the role of gender in shaping power dynamics and opportunities in society. The popularity of gender-neutral names reflects a broader shift toward inclusivity and the challenge of traditional gender roles.

*Source: <https://www.coe.int/en/web/gender-matters/exploring-gender-and-gender-identity#:~:text=Gender%20is%20of%20key%20importance,equality%20and%20freedom%20from%20discrimination>*

<p>&nbsp;</p>

Additonally, gender-neutral names empower girls and women by challenging gender stereotypes. According to a New York Times article, some parents opt for these names to counter biases and promote strength for their daughters.

*Source: <https://nypost.com/2018/03/21/why-gender-neutral-baby-names-are-on-the-rise/>*

<p>&nbsp;</p>

This trend aligns with the United Nations' Sustainable Development Goal 5, which aims to achieve gender equality and empower women and girls.

*Source: <https://sdgs.un.org/goals/goal5)](https://sdgs.un.org/goals/goal5>*

### (3) Which rows and columns of the dataset will be used to answer this question? (Answer: Actual names of the variables in the dataset that you plan to use).

I will use multiple datasets to answer the chosen question. 

Each dataset represents a specific year spanning from 1972 to 2022. In each dataset, there are 3 columns, corresponding to the name of the baby, the gender of the baby and the count of babies with that name and gender (The original dataset did not define the names of the variables, so I will redefine the variables as Name, Gender and Count). The number of rows, each corresponding to the observation for each name, differ for every dataset. 

Every row and column of the dataset will be used to answer my chosen question as all of them are relevant in comparing the shifts in naming trends over the years.

### (4) Challenges and errors that you faced and how you overcame them.

As the original dataset was a text file, I faced challenges in converting the text file to a csv file. I went online to search for the conversion technique and followed the steps accordingly. However, because the original text file has no title for each column, the columns in the csv output became named after the data in the first row of each column respectively, which is erroneous because the data in the first row are observations, not variables. I overcame this challenge by searching for more information online on how to convert text files without specific column names to csv.
